[package]
name = "unit_conversion"
version = "0.1.0"
edition = "2021"
authors = ["Sabrus <sab43@list.ru>"]

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
pathbuf = "1.0.0"
thiserror = "2.0.11"
once_cell = "1.20.2"